# Generated by Django 6.0.5 on 2026-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('tech', 'Tech'), ('seo', 'SEO')], max_length=20),
        ),
    ]
