# Generated by Django 6.0.5 on 2026-06-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic'), ('tech', 'Tech'), ('seo', 'SEO')], max_length=20),
        ),
    ]
