# Generated by Django 6.0.6 on 2026-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantfeature_departments_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeature',
            name='delivery_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantfeature',
            name='finance_module',
            field=models.BooleanField(default=True),
        ),
    ]
